// [This was generated by ChatGPT --ed]
// This simple adventure game takes place in a haunted house.
const hauntedHouse = () => ({
  roomId: 'hallway', // Set this to the ID of the room you want the player to start in.
  rooms: [
    {
      id: 'hallway',
      name: 'Hallway',
      desc: 'You are standing in a dark, spooky hallway. To the NORTH is a door to the Living Room. To the EAST is a door to the Dining Room.',
      exits: [
        {
          dir: 'north',
          id: 'livingRoom',
        },
        {
          dir: 'east',
          id: 'diningRoom',
        },
      ],
    },
    {
      id: 'livingRoom',
      name: 'Living Room',
      desc: 'You have entered a dusty living room. There is a CANDLE on a table in the center of the room. To the SOUTH is the Hallway.',
      items: [
        {
          name: 'candle',
          desc: 'A small, flickering candle that casts eerie shadows on the walls.',
          isTakeable: true,
          onTake() {
            println(`You have taken the ${this.name}.`);
          },
        },
      ],
      exits: [
        {
          dir: 'south',
          id: 'hallway',
        },
      ],
    },
    {
      id: 'diningRoom',
      name: 'Dining Room',
      desc: 'You have entered a grand dining room. The room is empty except for a TABLE set for dinner. To the WEST is the Hallway.',
      items: [
        {
          name: 'table',
          desc: 'An ornate dining table set for a large feast.',
          onUse() {
            println(`You sit down at the table, but there is no food. A chill runs down your spine.`);
          },
        },
      ],
      exits: [
        {
          dir: 'west',
          id: 'hallway',
        },
      ],
    },
  ]
});